eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: security

  datasource:
    url: jdbc:h2:mem:testdb4
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0